services:
  heliotrope:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heliotrope
    ports:
      - 8080:8080
    environment:
      # https://github.com/Saebasol/Heliotrope/blob/main/heliotrope/infrastructure/HELIOTROPE/config.py
      HELIOTROPE_USE_ENV: "true"
      HELIOTROPE_PRODUCTION: "true"
      HELIOTROPE_HOST: "0.0.0.0"
      HELIOTROPE_PORT: 8080
      HELIOTROPE_WORKERS: 25
      HELIOTROPE_SENTRY_DSN: ""
      HELIOTROPE_GALLERYINFO_DB_URL: mysql+asyncmy://heliotrope_user:heliotropepasswd@postgres-heliotrope-dev:5432/heliotrope_db
      HELIOTROPE_INFO_DB_URL: mongodb://heliotrope_user:heliotropepasswd@mongo-heliotrope-dev:27017
      HELIOTROPE_INDEX_FILES: '["index-japanese.nozomi"]'
      HELIOTROPE_MIRRORING_REMOTE_CONCURRENT_SIZE": 150
      HELIOTROPE_MIRRORING_LOCAL_CONCURRENT_SIZE": 250
